# Generated by Django 3.2.7 on 2021-12-10 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import image_cropping.fields
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Adresselinje 1', max_length=250)),
                ('postal_code', models.IntegerField(help_text='Postnummer')),
                ('city', models.CharField(help_text='Bynavn', max_length=250)),
                ('region', models.IntegerField(choices=[(1081, 'Region Nordjylland'), (1082, 'Region Midtjylland'), (1083, 'Region Syddanmark'), (1084, 'Region Hovedstaden'), (1085, 'Region Sjælland')], help_text='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel på eventet', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('external_link', models.URLField(help_text='Link til event på en ekstern side, hvis det findes. fx. billetto.dk')),
                ('location', models.CharField(help_text='Navn på stedet hvor eventet afholdes', max_length=200)),
                ('start_datetime', models.DateTimeField(help_text='Start dato og tidspunkt for eventet')),
                ('end_datetime', models.DateTimeField(help_text='Slut dato og tidspunkt for eventet')),
                ('summary', models.CharField(max_length=200)),
                ('description', markdownfield.models.MarkdownField(help_text='Beskrivelse af indholdet i eventet (markdown)', rendered_field='description_rendered')),
                ('description_rendered', markdownfield.models.RenderedMarkdownField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
            managers=[
                ('coming_events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(help_text='Billed der viser eventet. Vil blive vist på siden sammen med titlen', upload_to='images/%Y/%m/%d/')),
                ('cropping_detail', image_cropping.fields.ImageRatioField('image', '1850x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping detail')),
                ('cropping_list', image_cropping.fields.ImageRatioField('image', '900x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping list')),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
