# Generated by Django 3.2.7 on 2021-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Vejnavn og husnummer', max_length=250),
        ),
    ]
