# Generated by Django 3.2.7 on 2021-12-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(default=0, help_text='QR kode for tilmeldingen.', upload_to='event/registrations/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
