# Generated by Django 3.2.7 on 2021-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link til event på en ekstern side, hvis det findes. fx. billetto.dk', null=True),
        ),
    ]
