# Generated by Django 3.2.7 on 2021-12-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(help_text='QR kode for tilmeldingen.', upload_to='event/registrations/'),
        ),
    ]
