# Generated by Django 3.2.7 on 2021-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211219_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_manager_name': 'objects', 'ordering': ['-start_datetime']},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='maximum_attenders',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(help_text='QR kode for tilmeldingen.', upload_to='event/registrations/%Y/%m/%d/'),
        ),
    ]
