# Generated by Django 3.2.7 on 2022-01-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20211227_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maximum_attenders',
            new_name='maximum_attendees',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event'),
        ),
    ]
