# Generated by Django 3.2.7 on 2022-03-30 14:15

import ddsc_web.settings.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20220101_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(help_text='QR kode for tilmeldingen.', storage=ddsc_web.settings.custom_storages.PrivateMediaStorage(), upload_to='event/registrations/%Y/%m/%d/'),
        ),
    ]
