# Generated by Django 4.0.3 on 2022-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
