# Generated by Django 4.0.3 on 2022-05-30 19:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_calendar_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_rendered',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(help_text='Beskrivelse af indholdet i eventet (RTF)'),
        ),
    ]
