# Generated by Django 4.0.3 on 2022-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_event_description_rendered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='external_link',
            new_name='signup_link',
        ),
        migrations.AddField(
            model_name='event',
            name='signup_type',
            field=models.CharField(choices=[('DDSC', 'DDSC tilmelding'), ('External', 'Ekstern tilmelding')], default='DDSC', max_length=25),
            preserve_default=False,
        ),
    ]
