# Generated by Django 4.0.3 on 2022-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_external_link_event_signup_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signup_type',
            field=models.CharField(choices=[('DDSC', 'DDSC tilmelding'), ('External', 'Ekstern tilmelding')], help_text='Hvilken tilmeldingstype skal eventet have?', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Titel på eventet', max_length=200, unique=True),
        ),
    ]
