# Generated by Django 4.0.3 on 2022-06-12 14:42

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(help_text='Postnummer', max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='maximum_attendees',
            field=models.PositiveIntegerField(validators=[events.validators.validate_maximum_attendees]),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='order',
            field=models.PositiveIntegerField(validators=[events.validators.validate_image_order]),
        ),
    ]
