# Generated by Django 4.0.3 on 2022-06-12 17:22

from django.db import migrations, models
import events.validators
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(help_text='Postnummer', validators=[shared.validators.validate_fixed_digits]),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[events.validators.validate_image_order]),
        ),
    ]
