# Generated by Django 4.1.5 on 2023-03-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_address_postal_code_alter_eventimage_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="calendar_event_id",
        ),
    ]
