# Generated by Django 4.1.5 on 2023-03-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_remove_event_calendar_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="email",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="last_name",
        ),
    ]
