# Generated by Django 4.1.5 on 2023-03-26 07:28

from django.db import migrations
import events.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_remove_eventregistration_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="token",
            field=events.fields.TokenField(
                default=events.fields.generate_token, editable=False, max_length=32
            ),
        ),
    ]
