# Generated by Django 4.1.5 on 2023-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_eventregistration_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Attended", "Attended")],
                default="Pending",
                max_length=25,
            ),
        ),
    ]
