# Generated by Django 4.1.5 on 2023-03-27 19:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_eventregistration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms",
                    tinymce.models.HTMLField(
                        help_text="Vilkår for tilmelding til eventet (RTF)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Custom", "Custom"), ("Standard", "Standard")],
                        default="Standard",
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="registration_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.registrationterms",
            ),
        ),
    ]
