# Generated by Django 4.1.5 on 2023-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_registrationterms_event_registration_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationterms",
            name="name",
            field=models.CharField(default="DDSC Standard", max_length=200),
        ),
    ]
