# Generated by Django 4.1.5 on 2023-04-01 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_registrationterms_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationterms",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrationterms",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
