# Generated by Django 3.2.7 on 2022-03-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssubscriber_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssubscriber',
            old_name='confirmed',
            new_name='allow_newsletters',
        ),
        migrations.RemoveField(
            model_name='newssubscriber',
            name='email',
        ),
    ]
