# Generated by Django 4.1.5 on 2025-11-13 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220323_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssubscriber',
            options={'ordering': ['-created'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='confirmation_token',
            field=models.CharField(blank=True, help_text='Token for email confirmation', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for newsletter subscription', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='event_types',
            field=models.CharField(choices=[('all', 'All Events'), ('meetup', 'Meetups'), ('workshop', 'Workshops'), ('conference', 'Conferences'), ('webinar', 'Webinars')], default='all', help_text='Types of events to receive notifications about', max_length=50),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='frequency',
            field=models.CharField(choices=[('immediate', 'Immediate (as events are posted)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('monthly', 'Monthly Digest')], default='weekly', help_text='How often to receive newsletters', max_length=20),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the subscriber has confirmed their email'),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Subscriber's name", max_length=100),
        ),
        migrations.AddField(
            model_name='newssubscriber',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
