# Generated by Django 4.1.5 on 2025-11-13 18:15

from django.db import migrations
import secrets


def populate_email_from_user(apps, schema_editor):
    """Populate email field from user.email for existing subscribers"""
    NewsSubscriber = apps.get_model('news', 'NewsSubscriber')

    for subscriber in NewsSubscriber.objects.filter(email__isnull=True):
        if subscriber.user and subscriber.user.email:
            subscriber.email = subscriber.user.email
            subscriber.confirmation_token = secrets.token_urlsafe(48)
            subscriber.save()


def reverse_populate(apps, schema_editor):
    """No reverse operation needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newssubscriber_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_email_from_user, reverse_populate),
    ]
