# Generated by Django 3.2.7 on 2021-12-11 11:34

from django.db import migrations, models
import django.utils.timezone
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oprettet dato'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bestemmer om en bruger er aktiv eller ej', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Bestemmer om en bruger kan logge ind som administrator', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.fields.LowercaseEmailField(error_messages={'unique': 'A bruger er allerede oprettet med denne email adresse'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
