# Generated by Django 3.2.7 on 2021-12-11 12:03

from django.db import migrations, models
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211211_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.fields.LowercaseEmailField(error_messages={'unique': 'bruger er allerede oprettet med denne email adresse'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
