# Generated by Django 3.2.7 on 2021-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211211_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Bestemmer om brugeren har bekræftet validiteten af sin email', verbose_name='verified'),
        ),
    ]
