# Generated by Django 3.2.7 on 2021-12-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
