# Generated by Django 3.2.7 on 2021-12-18 18:47

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profileimage_cropping_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='cropping_member',
            field=image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping member'),
        ),
    ]
