# Generated by Django 3.2.7 on 2022-03-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profileimage_cropping_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
