# Generated by Django 3.2.7 on 2022-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votersession',
            name='vote_completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
