# Generated by Django 3.2.7 on 2022-02-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_votersession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('choice', 'question')},
        ),
    ]
