# Generated by Django 3.2.7 on 2022-02-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votersession',
            name='poll_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_sessions', to='polls.pollsession'),
        ),
    ]
