# Generated by Django 3.2.7 on 2022-02-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_alter_votersession_poll_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsession',
            name='author',
            field=models.ForeignKey(help_text='Forfatteren til afstemningen', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
