# Generated by Django 3.2.7 on 2021-12-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, choices=[('formand', 'Formand'), ('næstformand', 'Næstformand'), ('øvrigt medlem', 'Øvrigt medlem'), ('bestyrelsesmedlem', 'Bestyrelsesmedlem')], max_length=25)),
                ('user', models.OneToOneField(help_text='Medlem af foreningen DDSC', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
