# Generated by Django 3.2.7 on 2021-12-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Adresselinje 1', max_length=250)),
                ('postal_code', models.IntegerField(help_text='Postnummer')),
                ('city', models.CharField(help_text='Bynavn', max_length=250)),
                ('region', models.IntegerField(choices=[(1081, 'Region Nordjylland'), (1082, 'Region Midtjylland'), (1083, 'Region Syddanmark'), (1084, 'Region Hovedstaden'), (1085, 'Region Sjælland')], help_text='Region')),
                ('member', models.OneToOneField(help_text='Medlemsadresse, til kontingent betaling etc.', on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
