# Generated by Django 3.2.7 on 2021-12-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(help_text='Medlem af foreningen DDSC', on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
