# Generated by Django 3.2.7 on 2021-12-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.OneToOneField(help_text='Medlemsadresse, til kontingent betaling etc.', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='members.member'),
        ),
    ]
