# Generated by Django 3.2.7 on 2021-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_address_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
