# Generated by Django 3.2.7 on 2021-12-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_member_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Vejnavn og husnummer', max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Et valgfrit månedligt kontingent beløb', max_digits=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(error_messages={'unique': 'Du er allerede medlem af foreningen'}, help_text='Medlem af foreningen DDSC', on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
