# Generated by Django 3.2.7 on 2021-12-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20211211_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, choices=[('formand', 'Formand'), ('næstformand', 'Næstformand'), ('øvrigt medlem', 'Øvrigt medlem'), ('bestyrelsesmedlem', 'Bestyrelsesmedlem')], default='øvrigt medlem', max_length=25),
        ),
    ]
