# Generated by Django 3.2.7 on 2021-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Afventer godkendelse', 'Afventer godkendelse'), ('Aktiv', 'Aktiv')], default='Afventer godkendelse', help_text='Administrations felt til skift i medlemmers aktuelle status', max_length=20),
        ),
    ]
