# Generated by Django 3.2.7 on 2021-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1081, 'Region Nordjylland'), (1082, 'Region Midtjylland'), (1083, 'Region Syddanmark'), (1084, 'Region Hovedstaden'), (1085, 'Region Sjælland')], help_text='Region', null=True),
        ),
    ]
