# Generated by Django 3.2.7 on 2022-03-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_address_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription_amount',
        ),
    ]
