# Generated by Django 3.2.7 on 2022-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_member_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='job_title',
            field=models.CharField(blank=True, help_text='Din stillingsbetegnelse, fx. Data Analyst, Data Scientist, Data Engineer etc.', max_length=150, null=True, verbose_name='Titel'),
        ),
    ]
