# Generated by Django 4.0.3 on 2022-04-30 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_member_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.OneToOneField(help_text='Medlemsadresse til kontingent betaling etc.', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='members.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, choices=[('Formand', 'Formand'), ('Næstformand', 'Næstformand'), ('Øvrigt medlem', 'Øvrigt medlem'), ('Bestyrelsesmedlem', 'Bestyrelsesmedlem')], default='Øvrigt medlem', max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(error_messages={'unique': 'Du er allerede medlem af foreningen.'}, help_text='Medlem af foreningen DDSC', on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
