# Generated by Django 4.0.3 on 2022-06-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_address_member_alter_member_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(help_text='Postnummer', max_length=4),
        ),
    ]
