# Generated by Django 4.0.3 on 2022-06-12 17:22

from django.db import migrations, models
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(help_text='Postnummer', validators=[shared.validators.validate_fixed_digits]),
        ),
    ]
