# Generated by Django 4.1.5 on 2024-03-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("Afventer godkendelse", "Afventer godkendelse"),
                    ("Aktiv", "Aktiv"),
                ],
                default="Aktiv",
                help_text="Administrations felt til skift i medlemmers aktuelle status",
                max_length=20,
            ),
        ),
    ]
