# Generated by Django 4.1.5 on 2024-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_alter_member_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Formand", "Formand"),
                    ("Næstformand", "Næstformand"),
                    ("Øvrigt medlem", "Øvrigt medlem"),
                    ("Bestyrelsesmedlem", "Bestyrelsesmedlem"),
                    ("Suppleant", "Suppleant"),
                ],
                default="Øvrigt medlem",
                max_length=25,
            ),
        ),
    ]
