# Generated by Django 4.1.5 on 2023-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("question", models.CharField(db_index=True, max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("year", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["year", "question"],
            },
        ),
        migrations.AddIndex(
            model_name="surveydata",
            index=models.Index(
                fields=["question", "year"], name="stats_surve_questio_6feeda_idx"
            ),
        ),
    ]
