# Generated by Django 4.1.5 on 2023-07-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveydata",
            name="answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
