# Generated by Django 4.1.5 on 2023-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_surveydata_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveydata",
            name="answer",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="question",
            field=models.CharField(db_index=True, max_length=510),
        ),
    ]
