# Generated by Django 4.1.5 on 2023-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_alter_surveydata_answer_alter_surveydata_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveydata",
            name="answer",
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
    ]
