# Generated by Django 4.1.5 on 2023-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_alter_surveydata_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveydata",
            name="monthly_salary",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
