# Generated by Django 4.1.5 on 2023-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_surveydata_monthly_salary_alter_surveydata_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveydata",
            name="monthly_salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
